import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Book } from 'src/Book';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const books = [
      { id: 11, name: 'Egri csillagok', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 12, name: '1984', author: 'George Orwell', description: 'Nineteen Eighty-Four: A Novel, often published as 1984, is a dystopian novel by English novelist George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwells ninth and final book completed in his lifetime. The story was mostly written at Barnhill, a farmhouse on the Scottish island of Jura, at times while Orwell suffered from severe tuberculosis. Thematically, Nineteen Eighty-Four centres on the consequences of government over-reach, totalitarianism, mass surveillance, and repressive regimentation of all persons and behaviours within society.' , img: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/1984first.jpg/220px-1984first.jpg"},
      { id: 13, name: 'Brideshead Revisited', author: 'Evelyn Waugh', description: 'Evelyn Waugh bottles the intoxicating vapour of a vanished era in this novel about middle-class Charles Ryder, who meets upper-class Sebastian Flyte at Oxford University in the 1920s. Scrap the wartime prologue, and Charles’s entire relationship with Sebastian’s sister Julia (Dear Evelyn, thank you for your latest manuscript, a few suggested cuts…) and you’re looking at one of the most affecting love affairs in the English language.' , img: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/10/30/12/Brideshead-Revisited.jpg?w660"},
      { id: 14, name: 'Brideshead Revisited without img', author: 'Evelyn Waugh', description: 'Evelyn Waugh bottles the intoxicating vapour of a vanished era in this novel about middle-class Charles Ryder, who meets upper-class Sebastian Flyte at Oxford University in the 1920s. Scrap the wartime prologue, and Charles’s entire relationship with Sebastian’s sister Julia (Dear Evelyn, thank you for your latest manuscript, a few suggested cuts…) and you’re looking at one of the most affecting love affairs in the English language.' , img: ""},
      { id: 15, name: 'Egri csillagok II', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 16, name: 'Csillagok háborúja', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 17, name: 'Az új remény', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 18, name: 'Birodalom visszavág', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 19, name: 'Trabant', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 20, name: 'Napozz holdal', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 21, name: 'Az ember tervez', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},
      { id: 22, name: 'Sok jó ember kis helyen is after', author: 'Gárdonyi Géza', description: 'Az Egri csillagok Gárdonyi Géza 1899-től előbb folyóirat-folytatásokban megjelent, majd 1901-ben könyvben is kiadott regénye, az egyik legismertebb magyar történelmi regény, amelynek története a valóságos 1552. évi egri ostrom eseményeinek és előzményeinek történetét dolgozza fel érdekfeszítően cselekményes regény formájában. Cselekménye 1533-ban indul, és az 1552-es hatalmas túlerővel szemben diadalt aratott egri hősök győzelmével zárul. Az író maga e művét legjobb alkotásának tartotta. A regény 2005-ben, „A Nagy Könyv” elnevezésű országos felmérés eredményeként, melynek célja Magyarország legnépszerűbb regényének megválasztása volt, a Magyarország legkedveltebb regénye 2005 címet nyerte el.' , img: "https://kbimages1-a.akamaihd.net/9ace3e3c-18b1-413d-9152-63c9f7475a3c/353/569/90/False/egri-csillagok-4.jpg"},

    ];
    return {books};
  }
  genId(books: Book[]): number {
    return books.length > 0 ? Math.max(...books.map(book => book.id)) + 1 : 11;
  }
}
